### PR TITLE
Fix nightly issue

### PR DESCRIPTION
**Pull request by geoffroyleconte**
Related to https://github.com/JuliaSmoothOptimizers/SparseMatricesCOO.jl/pull/35

### CODE REVIEW

**Review by paraynaud — APPROVED** [review]

**Comment by dpo** [comment]
What was the issue with the strict option?

**Comment by geoffroyleconte** [comment]
> What was the issue with the strict option?

See the breaking changes here:
https://github.com/JuliaDocs/Documenter.jl/blob/v1.0.1/CHANGELOG.md

**Comment by amontoison** [comment]
Can you add a compat entry `Documenter = "1.0"` in the file `docs/Project.toml`?

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
Thanks Geoffroy!

**Pull request merged**
